### ISSUE TITLE
Initial release checklist

### ISSUE THREAD

**Issue by janoside** [janoside/lnd-admin#12]
- [x] Reduce node lookups
- [x] Withdraw funds, single address
- [x] Default to sats
- [x] Configure node with LND Connect string
- [x] Configure node with raw text strings
- [x] LND Connect page
