### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by janoside** [janoside/lnd-admin#14]
- [x] Install via npm
- [x] Commandline launch
- [x] Error 3297rgsd7gs7s
- [x] Caution note on withdraw page
- [x] Donation
